# I used this to create msg_control_codes.c. Keeping it around in case I need it later.

macros = """
#define EZTR_CC_COLOR_DEFAULT 00
#define EZTR_CC_COLOR_RED 01
#define EZTR_CC_COLOR_GREEN 02
#define EZTR_CC_COLOR_BLUE 03
#define EZTR_CC_COLOR_YELLOW 04
#define EZTR_CC_COLOR_LIGHTBLUE 05
#define EZTR_CC_COLOR_PINK 06
#define EZTR_CC_COLOR_SILVER 07
#define EZTR_CC_COLOR_ORANGE 08
#define EZTR_CC_TEXT_SPEED 0A
#define EZTR_CC_HS_BOAT_ARCHERY 0B
#define EZTR_CC_STRAY_FAIRIES 0C
#define EZTR_CC_TOKENS 0D
#define EZTR_CC_POINTS_TENS 0E
#define EZTR_CC_POINTS_THOUSANDS 0F
#define EZTR_CC_BOX_BREAK 10
#define EZTR_CC_NEWLINE 11
#define EZTR_CC_BOX_BREAK2 12
#define EZTR_CC_CARRIAGE_RETURN 13
#define EZTR_CC_SHIFT 14
#define EZTR_CC_CONTINUE 15
#define EZTR_CC_NAME 16
#define EZTR_CC_QUICKTEXT_ENABLE 17
#define EZTR_CC_QUICKTEXT_DISABLE 18
#define EZTR_CC_EVENT 19
#define EZTR_CC_PERSISTENT 1A
#define EZTR_CC_BOX_BREAK_DELAYED 1B
#define EZTR_CC_FADE 1C
#define EZTR_CC_FADE_SKIPPABLE 1D
#define EZTR_CC_SFX 1E
#define EZTR_CC_DELAY 1F
#define EZTR_CC_BTN_A B0
#define EZTR_CC_BTN_B B1
#define EZTR_CC_BTN_C B2
#define EZTR_CC_BTN_L B3
#define EZTR_CC_BTN_R B4
#define EZTR_CC_BTN_Z B5
#define EZTR_CC_BTN_CUP B6
#define EZTR_CC_BTN_CDOWN B7
#define EZTR_CC_BTN_CLEFT B8
#define EZTR_CC_BTN_CRIGHT B9
#define EZTR_CC_Z_TARGET BA
#define EZTR_CC_CONTROL_PAD BB
#define EZTR_CC_END BF
#define EZTR_CC_BACKGROUND C1
#define EZTR_CC_TWO_CHOICE C2
#define EZTR_CC_THREE_CHOICE C3
#define EZTR_CC_TIMER_POSTMAN C4
#define EZTR_CC_TIMER_MINIGAME_1 C5
#define EZTR_CC_TIMER_2 C6
#define EZTR_CC_TIMER_MOON_CRASH C7
#define EZTR_CC_TIMER_MINIGAME_2 C8
#define EZTR_CC_TIMER_ENV_HAZARD C9
#define EZTR_CC_TIME CA
#define EZTR_CC_CHEST_FLAGS CB
#define EZTR_CC_INPUT_BANK CC
#define EZTR_CC_RUPEES_SELECTED CD
#define EZTR_CC_RUPEES_TOTAL CE
#define EZTR_CC_TIME_UNTIL_MOON_CRASH CF
#define EZTR_CC_INPUT_DOGGY_RACETRACK_BET D0
#define EZTR_CC_INPUT_BOMBER_CODE D1
#define EZTR_CC_PAUSE_MENU D2
#define EZTR_CC_TIME_SPEED D3
#define EZTR_CC_OWL_WARP D4
#define EZTR_CC_INPUT_LOTTERY_CODE D5
#define EZTR_CC_SPIDER_HOUSE_MASK_CODE D6
#define EZTR_CC_STRAY_FAIRIES_LEFT_WOODFALL D7
#define EZTR_CC_STRAY_FAIRIES_LEFT_SNOWHEAD D8
#define EZTR_CC_STRAY_FAIRIES_LEFT_GREAT_BAY D9
#define EZTR_CC_STRAY_FAIRIES_LEFT_STONE_TOWER DA
#define EZTR_CC_POINTS_BOAT_ARCHERY DB
#define EZTR_CC_LOTTERY_CODE DC
#define EZTR_CC_LOTTERY_CODE_GUESS DD
#define EZTR_CC_HELD_ITEM_PRICE DE
#define EZTR_CC_BOMBER_CODE DF
#define EZTR_CC_EVENT2 E0
#define EZTR_CC_SPIDER_HOUSE_MASK_CODE_1 E1
#define EZTR_CC_SPIDER_HOUSE_MASK_CODE_2 E2
#define EZTR_CC_SPIDER_HOUSE_MASK_CODE_3 E3
#define EZTR_CC_SPIDER_HOUSE_MASK_CODE_4 E4
#define EZTR_CC_SPIDER_HOUSE_MASK_CODE_5 E5
#define EZTR_CC_SPIDER_HOUSE_MASK_CODE_6 E6
#define EZTR_CC_HOURS_UNTIL_MOON_CRASH E7
#define EZTR_CC_TIME_UNTIL_NEW_DAY E8
#define EZTR_CC_HS_POINTS_BANK_RUPEES F0
#define EZTR_CC_HS_POINTS_UNK_1 F1
#define EZTR_CC_HS_POINTS_FISHING F2
#define EZTR_CC_HS_TIME_BOAT_ARCHERY F3
#define EZTR_CC_HS_TIME_HORSE_BACK_BALLOON F4
#define EZTR_CC_HS_TIME_LOTTERY_GUESS F5
#define EZTR_CC_HS_TOWN_SHOOTING_GALLERY F6
#define EZTR_CC_HS_UNK_1 F7
#define EZTR_CC_HS_UNK_3_LOWER F8
#define EZTR_CC_HS_HORSE_BACK_BALLOON F9
#define EZTR_CC_HS_DEKU_PLAYGROUND_DAY_1 FA
#define EZTR_CC_HS_DEKU_PLAYGROUND_DAY_2 FB
#define EZTR_CC_HS_DEKU_PLAYGROUND_DAY_3 FC
#define EZTR_CC_DEKU_PLAYGROUND_NAME_DAY_1 FD
#define EZTR_CC_DEKU_PLAYGROUND_NAME_DAY_2 FE
#define EZTR_CC_DEKU_PLAYGROUND_NAME_DAY_3 FF
""".strip()

entries = {}

for row in macros.split("\n"):
    values = row.split(" ")
    
    name = values[1]
    hex = int(values[2], 16)
    
    entries[hex] = name
    
for i in range(0, 256):
    if i not in entries:
        print("NULL,")
    else:
        print(f"\"{entries[i]}\",")