name: Build and Publish mod
on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    outputs:
      thunderstore-package: ${{ steps.create-thunderstore-package.outputs.artifact-id }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Clang
      run: |-
        sudo apt install -y clang lld ninja-build
    - name: run-buildscript
      run: |-
        python3 ./create_thunderstore_package.py
    - name: create-thunderstore-package
      uses: actions/upload-artifact@v4
      with:
        name: ThunderstorePackage
        path: |
          ./thunderstore_package/*
          
    - name: publish-release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: ${{ github.ref }}
        body_path: ${{ github.workspace }}/thunderstore_package/CHANGELOG.md
        files: |
          ./build/mod/*.nrm
        make_latest: true
    
