name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    tags:
      - "release/"
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Clang
      run: |-
        sudo apt install -y clang lld ninja-build
    - name: run-buildscript
      run: |-
        python3 ./create_thunderstore_package.py
    - name: get-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ThunderstorePackage
        path: |
          ./thunderstore_package/*
    
