name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64
    - name: run-buildscript
      run: |-
        python3 ./build_mod.py
    - name: get-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: |
          ./build/*
    
